import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readdir,readFile } from 'node:fs/promises';
import test,{after} from 'node:test';
import {createServer} from 'vite';
const root=new URL('..',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1');
const vite=await createServer({appType:'custom',configFile:false,root,server:{middlewareMode:true,hmr:false}});after(()=>vite.close());
const {parseTransfer,transferUnusedWorkspace}=await vite.ssrLoadModule('/lib/server/workspace-transfer.ts');
const actor={userId:'operator',email:'operator@example.test',displayName:'Test operator'};
const command={fromAccountId:'qa',toAccountId:'internal',consoleClientId:'workspace-console',reason:'Correct test assignment',confirmed:true};
async function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of(await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));sqlite.exec("INSERT INTO accounts(id,name) VALUES('qa','QA'),('internal','Bearagon');INSERT INTO workspaces(id,account_id,slug,display_name,console_client_id) VALUES('original','qa','qa','QA','workspace-console')");
 const db={prepare(sql){const stmt={values:[],bind(...values){return {...stmt,values};},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...this.values).changes)}};}};return stmt;},async batch(statements){sqlite.exec('BEGIN');try{const r=statements.map(s=>s.run());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {sqlite,db};}
test('transfer requires explicit confirmation, reason and different accounts',()=>{assert.deepEqual(parseTransfer(command),command);for(const c of [{...command,confirmed:false},{...command,reason:''},{...command,toAccountId:'qa'}])assert.throws(()=>parseTransfer(c));});
test('transfer preserves source workspace, links destination and audits both accounts; repeat is inert',async()=>{const {sqlite,db}=await fixture();await transferUnusedWorkspace(db,command,actor);assert.equal(sqlite.prepare("SELECT console_client_id FROM workspaces WHERE id='original'").get().console_client_id,null);assert.equal(sqlite.prepare("SELECT console_client_id FROM workspaces WHERE account_id='internal'").get().console_client_id,'workspace-console');assert.deepEqual(sqlite.prepare('SELECT account_id FROM operator_audit_events ORDER BY account_id').all().map(r=>r.account_id),['internal','qa']);await assert.rejects(()=>transferUnusedWorkspace(db,command,actor),/Transfer not applied/);assert.equal(sqlite.prepare('SELECT count(*) n FROM operator_audit_events').get().n,2);sqlite.close();});
test('conflicting mappings, archived accounts and installations prevent all writes',async()=>{for(const sql of ["UPDATE workspaces SET console_client_id='changed'", "UPDATE accounts SET status='archived' WHERE id='internal'", "INSERT INTO workspaces(id,account_id,slug,display_name,console_client_id) VALUES('dest','internal','dest','Dest','other')", "INSERT INTO automation_blueprints(id,account_id,key,name,trigger_summary,action_summary) VALUES('bp','qa','bp','B','T','A');INSERT INTO automation_installations(id,account_id,workspace_id,blueprint_id) VALUES('i','qa','original','bp')"]){const {sqlite,db}=await fixture();sqlite.exec(sql);const before=sqlite.prepare('SELECT * FROM workspaces').all();await assert.rejects(()=>transferUnusedWorkspace(db,command,actor),/Transfer not applied/);assert.deepEqual(sqlite.prepare('SELECT * FROM workspaces').all(),before);assert.equal(sqlite.prepare('SELECT count(*) n FROM operator_audit_events').get().n,0);sqlite.close();}});
test('failure after unlink rolls back both mapping and audit',async()=>{const {sqlite,db}=await fixture();sqlite.exec("CREATE TRIGGER deny_link BEFORE UPDATE ON workspaces WHEN NEW.account_id='internal' BEGIN SELECT RAISE(ABORT,'fixture failure'); END;");await assert.rejects(()=>transferUnusedWorkspace(db,command,actor));assert.equal(sqlite.prepare("SELECT console_client_id FROM workspaces WHERE id='original'").get().console_client_id,'workspace-console');assert.equal(sqlite.prepare('SELECT count(*) n FROM operator_audit_events').get().n,0);sqlite.close();});
