"use client";
import { useEffect, useState } from "react";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AppShell } from "@/components/app-shell";

type Profile={tone:string;greeting:string;afterHours:string;emailStyle:string;disclose:boolean;payments:boolean;promises:boolean;sensitive:boolean;recording:boolean;urgentContact:string;businessHours:string};
const defaults:Profile={tone:"Calm and professional",greeting:"Thank you for calling Bearagon. I’m Cipher, Bearagon’s AI assistant. I can help understand what you need and make sure your message reaches the right person.",afterHours:"Our team is currently unavailable, but I can collect your message and mark anything urgent for review.",emailStyle:"Friendly, concise, and professional",disclose:true,payments:false,promises:false,sensitive:false,recording:false,urgentContact:"Derek Manchego",businessHours:"Monday–Friday · 8:00 AM–5:00 PM"};
const tabs=["Identity","Phone","Email","Guardrails","Escalation"];

export default function CipherControlCenter(){
 const[profile,setProfile]=useState<Profile>(defaults),[tab,setTab]=useState("Identity"),[saved,setSaved]=useState(""),[preview,setPreview]=useState(false);
 useEffect(()=>{try{const value=localStorage.getItem("cipher-operating-profile");if(value)setProfile({...defaults,...JSON.parse(value)})}catch{}},[]);
 function update<K extends keyof Profile>(key:K,value:Profile[K]){setProfile({...profile,[key]:value});setSaved("")}
 function save(){try{localStorage.setItem("cipher-operating-profile",JSON.stringify(profile))}catch{}setSaved("Operating profile saved")}
 return <AppShell><main className="cipher-page">
  <section className="cipher-hero"><div className="cipher-identity"><img src="/cipher-bearagon.png" alt="Cipher, Bearagon’s AI assistant"/><div><small>AI ASSISTANT PROFILE</small><h1>Cipher</h1><p>Bearagon’s secure front door for calls, messages, email, and client coordination.</p></div></div><div className="cipher-status"><i></i><span><b>Configuration mode</b><small>No live phone line connected</small></span></div></section>
  <div className="cipher-content">
   <section className="cipher-summary"><article><small>IDENTITY</small><strong>Clearly AI</strong><span>Disclosure required</span></article><article><small>PHONE MODE</small><strong>Message first</strong><span>Human escalation enabled</span></article><article><small>EMAIL MODE</small><strong>Draft only</strong><span>Human presses Send</span></article><article><small>HIGH-RISK ACTIONS</small><strong>Blocked</strong><span>No money or promises</span></article></section>
   <section className="cipher-workspace" id="cipher-settings">
    <nav className="cipher-tabs" aria-label="Cipher profile sections">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    <div className="cipher-editor">
     {tab==="Identity"&&<><div className="editor-heading"><small>IDENTITY & PERSONALITY</small><h2>How Cipher represents Bearagon</h2><p>One consistent identity across every client-facing channel.</p></div><div className="cipher-form-row"><label><span>Assistant name<small>Displayed to callers and clients</small></span><input value="Cipher" readOnly/></label><label><span>Role<small>Plain-language introduction</small></span><input value="Bearagon AI assistant" readOnly/></label></div><label className="cipher-field"><span>Communication tone<small>Applied to calls, messages, and drafts</small></span><Select value={profile.tone} onValueChange={value=>update("tone",value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Calm and professional">Calm and professional</SelectItem><SelectItem value="Warm and conversational">Warm and conversational</SelectItem><SelectItem value="Direct and concise">Direct and concise</SelectItem></SelectContent></Select></label><div className="identity-principles"><span><i>01</i><b>Never pretend to be human</b></span><span><i>02</i><b>Ask before assuming</b></span><span><i>03</i><b>Escalate when uncertain</b></span></div></>}
     {tab==="Phone"&&<><div className="editor-heading"><small>PHONE ANSWERING</small><h2>Opening and after-hours scripts</h2><p>Cipher uses approved language and never improvises business commitments.</p></div><label className="cipher-text"><span>Standard greeting<small>Used at the beginning of an answered call</small></span><Textarea value={profile.greeting} onChange={e=>update("greeting",e.target.value)}/></label><label className="cipher-text"><span>After-hours greeting<small>Used outside the approved schedule</small></span><Textarea value={profile.afterHours} onChange={e=>update("afterHours",e.target.value)}/></label><button className="preview-greeting" onClick={()=>setPreview(!preview)}>{preview?"Hide call preview":"Preview Cipher’s greeting"}</button>{preview&&<div className="greeting-preview"><img src="/cipher-bearagon.png" alt="" aria-hidden="true"/><span><small>CIPHER · LIVE PREVIEW</small><p>“{profile.greeting}”</p></span></div>}</>}
     {tab==="Email"&&<><div className="editor-heading"><small>EMAIL DRAFTING</small><h2>Helpful drafts, human sending</h2><p>Cipher prepares replies while the authorized user remains responsible for sending.</p></div><label className="cipher-field"><span>Drafting style<small>Default voice for welcome and follow-up emails</small></span><Select value={profile.emailStyle} onValueChange={value=>update("emailStyle",value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Friendly, concise, and professional">Friendly, concise, and professional</SelectItem><SelectItem value="Warm and detailed">Warm and detailed</SelectItem><SelectItem value="Brief and direct">Brief and direct</SelectItem></SelectContent></Select></label><div className="email-boundary"><b>Cipher may</b><b>Cipher may not</b><span>✓ Prepare welcome drafts</span><span>× Send automatically</span><span>✓ Summarize client messages</span><span>× Change recipients without review</span><span>✓ Suggest follow-up language</span><span>× Include unverified promises</span></div></>}
     {tab==="Guardrails"&&<><div className="editor-heading"><small>NON-NEGOTIABLE RULES</small><h2>What Cipher can never decide alone</h2><p>High-impact permissions remain off unless a client explicitly approves a future workflow.</p></div><div className="cipher-switches"><Rule label="AI identity disclosure" note="Cipher identifies itself clearly at the start." checked={profile.disclose} change={v=>update("disclose",v)}/><Rule label="Accept payments" note="Disabled. Cipher cannot collect card or bank details." checked={profile.payments} change={v=>update("payments",v)}/><Rule label="Promise pricing or outcomes" note="Disabled. Quotes and commitments require a person." checked={profile.promises} change={v=>update("promises",v)}/><Rule label="Reveal sensitive account data" note="Disabled even when the caller claims to be a client." checked={profile.sensitive} change={v=>update("sensitive",v)}/><Rule label="Record or transcribe calls" note="Off until an approved consent policy is configured." checked={profile.recording} change={v=>update("recording",v)}/></div></>}
     {tab==="Escalation"&&<><div className="editor-heading"><small>HUMAN HANDOFF</small><h2>When Cipher stops and calls a person</h2><p>Urgent, sensitive, uncertain, or dissatisfied callers receive a clear handoff.</p></div><div className="cipher-form-row"><label><span>Primary escalation contact<small>First person notified</small></span><input value={profile.urgentContact} onChange={e=>update("urgentContact",e.target.value)}/></label><label><span>Business hours<small>Controls normal and after-hours scripts</small></span><input value={profile.businessHours} onChange={e=>update("businessHours",e.target.value)}/></label></div><div className="escalation-list"><span><i>Immediate</i><b>Threats, emergencies, security concerns</b></span><span><i>Priority</i><b>Service outage, angry client, same-day deadline</b></span><span><i>Routine</i><b>Appointment, billing question, general message</b></span><span><i>Filtered</i><b>Spam, solicitation, unverifiable request</b></span></div></>}
    </div>
    <footer className="cipher-save"><span>{saved||"Changes remain in configuration mode until saved."}</span><button onClick={save}>Save operating profile</button></footer>
   </section>
   <section className="cipher-safety-note"><img src="/cipher-bearagon.png" alt="" aria-hidden="true"/><div><small>CIPHER’S OPERATING PROMISE</small><h2>Helpful within limits. Human when it matters.</h2><p>Every client can review and approve their own version before activation.</p></div><a href="/communications">Open Calls & Messages →</a></section>
  </div>
 </main></AppShell>
}
function Rule({label,note,checked,change}:{label:string;note:string;checked:boolean;change:(v:boolean)=>void}){return <label><span><b>{label}</b><small>{note}</small></span><Switch checked={checked} onCheckedChange={change}/></label>}
