"use client";
import {CompanyRemoval} from './company-removal';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from './app-shell';
import { CompanyJourney } from './company-journey';
import { ProposalWorkspace } from './proposal-workspace';
import { AccountRelationship } from './account-relationship';
import { AccountServices, ServiceSummary } from './account-services';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Textarea } from './ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from './ui/dialog';
import { companySection, journeyPhase, journeyLabels, phaseSection, companyView, companyDestination, type CompanyView, type CompanySection } from '@/lib/company-journey';
import { OwnerSelect } from './owner-select';
import { InternalOverview } from './internal-overview';
import { InternalPortfolio } from './internal-portfolio';
import { RequirementEditor } from './requirement-editor';
import { requirementRowDetail } from '@/lib/requirement-readiness';
import { deliveryReadiness } from '@/lib/delivery-readiness';
import { DeliveryNextAction } from './delivery-next-action';
import type { ProposalState } from '@/lib/proposal-model';

import { WebsiteResearch } from './website-research';
import { researchNotes } from '@/lib/company-research';

type Client={accountStatus?:string;website:string;salesStage:string;relationshipOwner:string;followUpDate:string;relationshipNextAction:string;id:string;companyName:string;contactName:string;email:string;phone:string;stage:string;nextStep:string;dueDate:string;notes:string;relationshipType:string;organizationKind:string;onboardingStatus:string};
type Task={id:string;templateKey:string;title:string;description:string;status:string;evidenceRef:string;completionNote:string;blockedReason:string};
type Detail={client:Client;tasks:Task[];activity:{id:string;action:string;actorName:string;createdAt:string;result:string;detail:string}[];workspace:{lifecycle:string}|null};
const terminal=(t:Task)=>['completed','skipped'].includes(t.status);
const setupKeys=['agreement','discovery','communications','business_system','guardrails'];
async function json<T>(url:string,body?:unknown):Promise<T>{const r=await fetch(url,{cache:'no-store',...(body?{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json() as T & {error?:string};if(!r.ok)throw Error(d.error||'Unable to load or save this record.');return d;}

export function CompanyWorkspace({workspace='company'}:{workspace?:'company'|'onboarding'}){
  const {id}=useParams<{id:string}>(),router=useRouter(),query=useSearchParams();
  const section=companySection(query.get('tab')||(workspace==='onboarding'?'services':null));
  const [detail,setDetail]=useState<Detail|null>(null),[proposal,setProposal]=useState<ProposalState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [notes,setNotes]=useState(''),[target,setTarget]=useState(''),[next,setNext]=useState(''),[savedNotes,setSavedNotes]=useState(''),[notice,setNotice]=useState('');
  const [operationsOwner,setOperationsOwner]=useState('');
  const [website,setWebsite]=useState('');
  const [task,setTask]=useState<Task|null>(null),[launch,setLaunch]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [nestedBusy,setNestedBusy]=useState(false),[checkingTask,setCheckingTask]=useState(false);
  const requirementDrafts=useRef(new Map<string,Task>());
  const [proposalDirty,setProposalDirty]=useState(false),[relationshipDirty,setRelationshipDirty]=useState(false);
  const title=useRef<HTMLHeadingElement>(null),mutation=useRef(false);
  const apply=useCallback((d:Detail)=>{setDetail(d);setWebsite(d.client.website||'');setOperationsOwner(d.client.relationshipOwner);setNotes(d.client.notes);setSavedNotes(d.client.notes);setTarget(d.client.dueDate);setNext(d.client.nextStep);},[]);
  const load=useCallback(async()=>{setError('');try{const [d,p]=await Promise.all([json<Detail>(`/api/clients/${id}`),json<{proposal:ProposalState}>(`/api/clients/${id}/proposal`)]);apply(d);setProposal(p.proposal);}catch(e){setError((e as Error).message);}},[id,apply]);
  useEffect(()=>{void load();},[load]);
  const proposalSaved=useCallback((p:ProposalState)=>{setProposal(p);void json<Detail>(`/api/clients/${id}`).then(d=>setDetail(d)).catch(e=>setError(e.message));},[id]);
  const dirty=!!detail&&website!==(detail.client.website||'')||!!detail&&detail.client.organizationKind==='internal'&&operationsOwner!==detail.client.relationshipOwner||proposalDirty||relationshipDirty||notes!==savedNotes||!!task&&detail?.client.onboardingStatus!=='completed'&&JSON.stringify(task)!==JSON.stringify(detail?.tasks.find(t=>t.id===task.id))||requirementDrafts.current.size>0||!!detail&&(target!==detail.client.dueDate||next!==detail.client.nextStep);
  function go(tab:CompanySection, destination?:CompanyView){setNotice('');if(busy||nestedBusy)return;if(dirty&&!window.confirm('Leave this section and discard unsaved changes?'))return;setProposalDirty(false);setRelationshipDirty(false);requirementDrafts.current.clear();setTask(null);if(detail){setWebsite(detail.client.website||'');setOperationsOwner(detail.client.relationshipOwner);setNotes(detail.client.notes);setSavedNotes(detail.client.notes);setTarget(detail.client.dueDate);setNext(detail.client.nextStep);}router.push(companyDestination(id,tab,phase,destination||(tab==='activity'?view:undefined),!!internal),{scroll:true});}
  useEffect(()=>{title.current?.focus();window.scrollTo({top:0,behavior:'instant'});},[section]);
  useEffect(()=>{const leave=(e:MouseEvent)=>{if(!proposalDirty&&dirty&&(e.target as Element)?.closest('a[href]:not([target="_blank"])')&&!window.confirm('Leave and discard unsaved company changes?')){e.preventDefault();e.stopPropagation();}};document.addEventListener('click',leave,true);const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',leave,true);};},[dirty]);
  async function mutate(body:unknown){if(mutation.current)return false;mutation.current=true;setBusy(true);setError('');setNotice('');try{await json(`/api/clients/${id}`,body);const d=await json<Detail>(`/api/clients/${id}`);apply(d);return true;}catch(e){setError((e as Error).message);return false;}finally{mutation.current=false;setBusy(false);}}
  async function saveContext(){
    if(mutation.current||!detail)return;
    mutation.current=true;setBusy(true);setError('');setNotice('');
    try{
      const saved=await json<{website:string;notes:string}>(`/api/clients/${id}/context`,{website,notes,expectedWebsite:detail.client.website||'',expectedNotes:savedNotes});
      setDetail(d=>d?{...d,client:{...d.client,...saved}}:d);setWebsite(saved.website);setNotes(saved.notes);setSavedNotes(saved.notes);setNotice('Company context saved.');
    }catch(e){setError((e as Error).message);}finally{mutation.current=false;setBusy(false);}
  }
  async function saveOwner(){
    if(mutation.current||!detail)return;
    mutation.current=true;setBusy(true);setError('');setNotice('');
    try {
      const saved=await json<{owner:string}>(`/api/clients/${id}/operations-owner`,{owner:operationsOwner,expectedOwner:detail.client.relationshipOwner});
      setDetail(d=>d?{...d,client:{...d.client,relationshipOwner:saved.owner}}:d);
      setOperationsOwner(saved.owner);setNotice('Operations owner saved.');
    }catch(e){setError((e as Error).message);}finally{mutation.current=false;setBusy(false);}
  }
  const client=detail?.client;
  const phase=client?journeyPhase(client,proposal):0;
  const view=companyView(section,phase,workspace);
  const closed=client?.onboardingStatus==='completed';
  const internal=client?.organizationKind==='internal';
  const requirements=(detail?.tasks||[]).filter(t=>!t.templateKey?.startsWith('scope:'));
  const readiness=deliveryReadiness(client?.onboardingStatus||'not_started',detail?.tasks||[],proposal);
  const ready=readiness.ready;
  async function finish(){if(!confirmed||!ready||mutation.current)return;setError('');setBusy(true);mutation.current=true;try{await json(`/api/clients/${id}`,{stage:'Live'});await json(`/api/clients/${id}`,{completeOnboarding:true});const d=await json<Detail>(`/api/clients/${id}`);apply(d);setLaunch(false);setConfirmed(false);router.push(companyDestination(id,'complete',4));}catch(e){setError((e as Error).message);void json<Detail>(`/api/clients/${id}`).then(setDetail);}finally{mutation.current=false;setBusy(false);}}
  async function openTask(t:Task){if(busy||checkingTask)return;if(task&&JSON.stringify(task)!==JSON.stringify(detail?.tasks.find(t=>t.id===task.id)))requirementDrafts.current.set(task.id,{...task});setCheckingTask(true);setError('');try{const fresh=await json<Detail>(`/api/clients/${id}`);setDetail(fresh);const current=fresh.tasks.find(item=>item.id===t.id);if(!current)throw Error('This requirement is no longer available.');setTask(fresh.client.onboardingStatus==='completed'?{...current}:{...(requirementDrafts.current.get(t.id)||current)});}catch(e){setError((e as Error).message);}finally{setCheckingTask(false);}}
  function closeTask(){if(busy||checkingTask)return;if(!closed&&JSON.stringify(task)!==JSON.stringify(detail?.tasks.find(t=>t.id===task?.id))&&!window.confirm('Discard this unsaved requirement edit?'))return;if(task)requirementDrafts.current.delete(task.id);setTask(null);setError('');}
  async function saveRequirement(value:Task){setTask(value);if(await mutate({taskId:value.id,status:value.status,evidenceRef:value.evidenceRef,completionNote:value.completionNote,blockedReason:value.status==='blocked'?value.blockedReason:''})){requirementDrafts.current.delete(value.id);setTask(null);setNotice('Requirement saved.');}else{void json<Detail>(`/api/clients/${id}`).then(setDetail).catch(()=>{});}}
  function requirementsPanel(){return <section className="company-panel"><div className="panel-heading"><div><small className="eyebrow">DELIVERY REQUIREMENTS</small><h2>Connections, approvals & launch</h2></div><span className="company-status">{requirements.filter(terminal).length}/{requirements.length} resolved</span></div><p className="company-help">Review the saved evidence or record an approved exception. Completed requirements remain available for inspection. Unsaved drafts are kept on this page while you open prerequisites; return to save them before leaving.</p>{[['Setup & access',requirements.filter(t=>setupKeys.includes(t.templateKey))],['Build, client testing & launch',requirements.filter(t=>!setupKeys.includes(t.templateKey))]].map(([label,rows])=><div key={label as string}><h3>{label as string}</h3>{(rows as Task[]).map(t=><button className={`company-requirement ${t.status}`} key={t.id} disabled={busy||checkingTask} onClick={()=>void openTask(t)}><span><b>{t.title}</b><small>{requirementRowDetail(t,requirements,closed)}</small></span><em>{requirementDrafts.current.has(t.id)?'Unsaved draft':t.status.replaceAll('_',' ')}</em></button>)}</div>)}{!closed&&<div className="company-actions"><Button disabled={!ready||busy} onClick={()=>{setConfirmed(false);setLaunch(true);}}>Review & complete onboarding →</Button><span className="company-help">{ready?'Ready for your final handoff review.':'Resolve every requirement and current work-order evidence before launch.'}</span></div>}</section>;}
  if(client?.accountStatus==='archived')return <AppShell activeSection="/companies"><main className="company-experience"><Link href="/companies">← Companies</Link><h1>{client.companyName}</h1><p className="company-notice">Archived from active Ops listings. Saved records remain available here.</p><section className="company-panel"><h2>Company information</h2><p>{client.contactName} · {client.email}</p><p>{client.phone}</p><p>{client.website}</p><p style={{whiteSpace:'pre-wrap'}}>{client.notes}</p></section><details className="company-panel"><summary>Saved delivery records</summary>{detail?.tasks.map(t=><article key={t.id}><h3>{t.title} · {t.status}</h3><p>{t.completionNote||t.description}</p><p>{t.evidenceRef}</p></article>)}</details><section className="company-panel"><h2>Activity & removal history</h2>{detail?.activity.map(e=><article key={e.id}><h3>{e.action}</h3><p>{e.actorName} · {e.createdAt}</p><p>{e.detail}</p></article>)}</section></main></AppShell>;
  if(internal&&client)return <AppShell activeSection="/operations"><main className="company-experience"><header className="company-record-header"><div><div className="record-breadcrumb"><Link href="/operations">Operations</Link><span>/ {client.companyName}</span></div><h1 ref={title} tabIndex={-1}>{client.companyName}</h1><p>Internal operations · continuous improvement, not client onboarding</p></div></header><nav className="company-section-tabs" aria-label="Internal operations sections">{(['overview','services','delivery','activity'] as const).map(t=><button key={t} aria-current={section===t?'page':undefined} className={section===t?'active':''} onClick={()=>go(t)}>{({overview:'Overview',services:'Services & monitoring',delivery:'Automation work',activity:'Activity'})[t]}</button>)}</nav>{error&&<p role="alert" className="company-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {section==='overview'&&<InternalOverview proposal={proposal} owner={client.relationshipOwner} ownerEditor={<form onSubmit={e=>{e.preventDefault();void saveOwner();}}><fieldset className="operations-owner-fields" disabled={busy||nestedBusy}><label>Assigned to<OwnerSelect value={operationsOwner} onChange={setOperationsOwner}/></label><p className="company-help">Responsible for coordinating Bearagon’s internal work.</p><Button type="submit" disabled={operationsOwner===client.relationshipOwner}>{busy?'Saving…':'Save owner'}</Button></fieldset></form>} notes={client.notes} onWork={()=>go('delivery')} onServices={()=>go('services')} onPlan={()=>go('services')}/>}
    {(section==='delivery'||section==='complete')&&<><InternalPortfolio accountId={id} proposal={proposal} onSaved={proposalSaved} onDirty={setProposalDirty} onBusy={setNestedBusy} onPlan={()=>go('services')}/><details className="company-panel"><summary>Shared setup, original build briefs & revision history</summary><ProposalWorkspace setupOnly accountId={id} mode="delivery" onSaved={proposalSaved} onDirty={setRelationshipDirty} onBusy={setNestedBusy} onScope={()=>go('services')}/></details><details className="company-panel"><summary>Prior onboarding checklist — retained history</summary><p>This checklist is not a company-wide completion gate. Its notes remain unchanged; current safety approval is recorded per automation.</p>{requirements.map(t=><article className="internal-order" key={t.id}><h3>{t.title}</h3><p>{t.status}</p><p>{t.completionNote||t.description}</p>{t.evidenceRef&&<p>{t.evidenceRef}</p>}{t.blockedReason&&<p>Recorded blocker: {t.blockedReason}</p>}</article>)}</details></>}
    {section==='services'&&<><AccountServices accountId={id} companyName={client.companyName}/><details className="company-panel" open={!proposal?.acceptance}><summary>Internal plan & shared setup</summary><ProposalWorkspace accountId={id} mode="services" onSaved={proposalSaved} onDirty={setProposalDirty} onBusy={setNestedBusy} onDelivery={()=>go('delivery')}/></details><Button onClick={()=>go('delivery')}>Open automation work</Button></>}
    {section==='activity'&&<section className="company-panel"><h2>Internal operations history</h2>{detail?.activity.map(e=><article key={e.id}><h3>{e.action.replaceAll('_',' ')}</h3><p>{e.actorName} · {e.createdAt}</p><p>{e.detail}</p></article>)}</section>}
  </main></AppShell>;
  return <AppShell activeSection={view==='company'?'/companies':view==='onboarding'?'/onboarding':'/operations'}><main className="company-experience">
    {!client?<section className="company-panel"><h1>{error?'Unable to open company':'Loading company…'}</h1>{error&&<><p role="alert">{error}</p><Button onClick={()=>void load()}>Try again</Button></>}</section>:<>
      <header className="company-record-header"><div><div className="record-breadcrumb"><Link href={view==='company'?'/companies':view==='onboarding'?'/onboarding':'/operations'}>{view==='company'?'Companies':view==='onboarding'?'Onboarding':'Operations'}</Link><span>/</span><span>{client.companyName}</span></div><h1 ref={title} tabIndex={-1}>{client.companyName}</h1><p>{[client.contactName,client.email,client.phone].filter(Boolean).join(' · ')||'No primary contact recorded'}</p></div><div className="company-view-actions">{view==='company'&&<CompanyRemoval accountId={id} companyName={client.companyName} disabled={!!dirty||busy||nestedBusy}/>}<span className="company-status">{view==='company'?(client.relationshipType==='client'?'Client':'Prospect'):phase===2||phase===3?readiness.stageLabel:journeyLabels[phase]}</span>{view==='company'?<Button variant="outline" onClick={()=>go(phase===4?'services':phase<2?'services':'delivery')}>{phase===4?'Open operations':'Open onboarding'} →</Button>:<Button variant="outline" onClick={()=>go('overview')}>Company profile →</Button>}</div></header>
      {view==='onboarding'&&<CompanyJourney phase={phase} onNavigate={p=>go(phaseSection(p))}/>}
      <nav className="company-section-tabs" aria-label={view==='company'?'Company information':view==='onboarding'?'Onboarding sections':'Operations sections'}>{(view==='company'?(['overview','activity'] as const):view==='onboarding'?(['services','delivery','activity'] as const):(['services'] as const)).map(t=><button key={t} className={section===t?'active':''} aria-current={section===t?'page':undefined} onClick={()=>go(t,view)}>{view==='company'?(t==='overview'?'Overview':'Activity'):t==='services'?(view==='operations'?'Services & monitoring':'Scope & order'):t==='delivery'?'Setup & delivery':'History'}</button>)}</nav>
      {error&&<div className="company-error" role="alert">{error}</div>}{notice&&<div className="company-notice" role="status">{notice}</div>}
      {section==='overview'&&<div className="company-record-grid"><div className="company-record-main"><section className="company-panel"><small className="eyebrow">COMPANY INFORMATION</small><h2>Website & company notes</h2><WebsiteResearch website={website} onWebsiteChange={setWebsite} disabled={busy||nestedBusy} notesOnly onApply={(result,fields,ideas)=>{const extra=researchNotes(result,fields,ideas);const updated=[notes,extra].filter(Boolean).join('\n\n');if(updated.length>5000){setError('These suggestions exceed the 5,000-character notes limit. Select fewer items or shorten your notes.');return false;}setNotes(updated);setWebsite(result.website);setNotice('Suggestions added to your notes draft. Review and save company context.');return true;}}/><label htmlFor="company-notes">What should the next person know?</label><Textarea id="company-notes" maxLength={5000} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)}/><div className="company-actions"><Button disabled={busy||nestedBusy||notes===savedNotes&&website===(client.website||'')} onClick={()=>void saveContext()}>Save company context</Button></div></section><AccountRelationship accountId={id} ongoing={phase===4} onDirty={setRelationshipDirty} onRelationshipChange={()=>{void json<Detail>(`/api/clients/${id}`).then(setDetail).catch(e=>setError(e.message));}}/></div><aside className="company-record-side"><section className="company-panel"><small className="eyebrow">PEOPLE & OWNERSHIP</small><h2>{client.contactName||'Primary contact not set'}</h2><p>{client.email}<br/>{client.phone}</p><h3>Bearagon owner</h3><p>{client.relationshipOwner||'Unassigned'}</p><h3>Follow-up due</h3><p>{client.followUpDate||'Not scheduled'}</p><p className="company-help">{client.relationshipNextAction||'Assign the next conversation in the relationship form.'}</p><Link href="/communications">Open inquiry follow-up →</Link></section><ServiceSummary accountId={id} openServices={()=>go('services')}/></aside></div>}
      {section==='services'&&<><details className="company-panel"><summary>Workspace setup</summary><section className="company-panel"><small className="eyebrow">OPERATIONAL WORKSPACE</small><h2>{detail.workspace?.lifecycle||'Not provisioned'}</h2><p className="company-help">Workspace provisioning and Console reporting remain separate from accepted scope.</p>{!detail.workspace&&<Button variant="outline" disabled={busy} onClick={async()=>{if(await mutate({requestWorkspace:true}))setNotice('Workspace requested. Provisioning and reporting remain separate.');}}>Request workspace</Button>}</section></details>{phase===4&&<AccountServices accountId={id} companyName={client.companyName}/>}<details className="company-scope-container" open={phase!==4||query.get('step')==='review'}><summary>{proposal?.acceptance?'Agreed services & commercial terms':'Establish the service package'}</summary><ProposalWorkspace key={`${id}-services`} accountId={id} mode="services" onSaved={proposalSaved} onDirty={setProposalDirty} onBusy={setNestedBusy} onDelivery={()=>{setProposalDirty(false);router.push(companyDestination(id,'delivery',phase));}}/></details>{phase!==4&&<details className="company-panel"><summary>Existing services & Console configuration</summary><p className="company-help">Previously recorded services remain here. They are not silently imported into a new quote.</p><AccountServices accountId={id} companyName={client.companyName}/></details>}</>}
      {section==='delivery'&&<>{!closed&&<section className="company-panel company-next"><DeliveryNextAction readiness={readiness} coordination={client.nextStep}/>{ready&&<Button disabled={busy} onClick={()=>{setConfirmed(false);setLaunch(true);}}>Review & complete onboarding →</Button>}</section>}{closed&&<section className="company-panel"><small className="eyebrow">DELIVERY COMPLETE</small><h2>Now in ongoing service</h2><p>The saved delivery history stays here. Current reporting is in Services & monitoring.</p><div className="company-actions"><Button onClick={()=>go('services')}>Go to ongoing operations →</Button><Button variant="outline" onClick={()=>go('complete')}>View completion milestone</Button></div></section>}{!readiness.legacy&&<ProposalWorkspace key={`${id}-delivery-${closed}`} accountId={id} mode="delivery" onSaved={proposalSaved} onDirty={setProposalDirty} onScope={()=>go('services')}>{!closed&&requirementsPanel()}</ProposalWorkspace>}{!closed&&readiness.legacy&&<section className="company-panel"><h2>Existing delivery plan</h2><p>This engagement uses its existing delivery requirements. Package history is not recorded; the saved requirements and evidence remain available below.</p>{requirementsPanel()}</section>}{closed&&requirementsPanel()}{!closed&&requirements.length>0&&<details className="company-panel"><summary>Delivery coordination</summary><label>Coordination note<Input value={next} onChange={e=>setNext(e.target.value)}/></label><label>Target date<Input type="date" value={target} onChange={e=>setTarget(e.target.value)}/></label><Button disabled={busy} onClick={async()=>{if(await mutate({nextStep:next,targetDate:target}))setNotice('Delivery coordination saved.');}}>Save coordination</Button></details>}</>}
      {section==='activity'&&<section className="company-panel"><h2>Relationship & delivery history</h2><p className="company-help">Recorded operator actions. Runtime observations are shown separately in Services.</p>{detail.activity.length?detail.activity.map(e=><article className="company-requirement" key={e.id}><div><b>{e.action.replaceAll('_',' ').replaceAll('.',' · ')}</b><small>{e.actorName} · {e.result} · {new Date(e.createdAt).toLocaleString()}</small><p>{e.detail}</p></div></article>):<p>No activity recorded yet.</p>}</section>}
      {section==='complete'&&(closed&&client.stage==='Live'?<section className="company-completion"><div className="company-completion-copy"><small className="eyebrow">ONBOARDING COMPLETE</small><h2>A great start.<br/>An ongoing partnership.</h2><p>{client.companyName} has crossed the onboarding finish line. The team’s preparation, verification and handoff are recorded.</p><p>✓ Delivery requirements resolved<br/>✓ Authorized handoff recorded<br/>✓ History retained for the next chapter</p><Button onClick={()=>go('services')}>Go to ongoing operations →</Button><p className="company-help">Completion records delivery readiness—not current runtime health. Check Console reporting in Services.</p></div><img src="/cipher-completion.png" alt="Cipher celebrating the onboarding finish line"/></section>:<section className="company-panel"><h2>Finish the handoff first</h2><p>The completion milestone opens only after onboarding is saved as complete.</p><Button onClick={()=>go('delivery')}>Return to delivery</Button></section>)}
    </>}
    {checkingTask&&<p className="company-notice" role="status">Checking the latest requirement status…</p>}
    <Dialog open={!!task} onOpenChange={open=>{if(!open)closeTask();}}><DialogContent className="crm-dialog"><DialogHeader><DialogTitle>{task?.title}</DialogTitle><DialogDescription>{task?.description}</DialogDescription></DialogHeader>{task&&<RequirementEditor key={task.id} task={task} tasks={requirements} proposal={proposal} closed={closed} busy={busy||checkingTask} error={error} onChange={setTask} onSave={saveRequirement} onClose={closeTask} onOpen={t=>void openTask(t)}/>}</DialogContent></Dialog>
    <Dialog open={launch} onOpenChange={open=>{if(!busy)setLaunch(open);}}><DialogContent><DialogHeader><DialogTitle>Approve the onboarding handoff</DialogTitle><DialogDescription>Record the transition to ongoing service. This does not deploy an automation or certify runtime health.</DialogDescription></DialogHeader><ul><li>{requirements.filter(terminal).length} delivery requirements resolved</li><li>{proposal?.acceptance?`${proposal.orders.length} service work orders with current external evidence`:'Existing engagement evidence retained'}</li><li>Launch approval requirement recorded</li></ul><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I am authorized to complete this handoff.</label>{error&&<p role="alert">{error}</p>}<DialogFooter><Button disabled={busy||!confirmed||!ready} onClick={()=>void finish()}>{busy?'Saving handoff…':'Complete onboarding →'}</Button></DialogFooter></DialogContent></Dialog>
  </main></AppShell>;
}
