"use client";
import {useEffect,useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from './ui/dialog';
import {serviceCatalog} from '@/lib/proposal-scope';
import {internalStage} from '@/lib/internal-operations';
import type {ProposalState,ProposalCommand,WorkOrder} from '@/lib/proposal-model';
import {EmailWalkthroughLink} from './email-walkthrough-link';

export function InternalPortfolio({accountId,proposal,onSaved,onPlan,onDirty,onBusy}:{accountId:string;proposal:ProposalState|null;onSaved:(p:ProposalState)=>void;onPlan:()=>void;onDirty:(value:boolean)=>void;onBusy:(value:boolean)=>void}) {
  const [edit,setEdit]=useState<WorkOrder|null>(null),[adding,setAdding]=useState(false),[reviewing,setReviewing]=useState<WorkOrder|null>(null);
  const [name,setName]=useState(''),[brief,setBrief]=useState(''),[review,setReview]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
  const dirty=!!edit||adding||!!reviewing;
  useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  async function save(command:Omit<ProposalCommand,'expectedVersion'>){if(!proposal||busy)return;setBusy(true);setError('');try{const r=await fetch(`/api/clients/${accountId}/proposal`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...command,expectedVersion:proposal.version})});const data=await r.json() as {proposal:ProposalState;error?:string};if(!r.ok)throw Error(data.error||'Save failed.');onSaved(data.proposal);setEdit(null);setAdding(false);setReviewing(null);setName('');setBrief('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function close(){if(busy)return;if(dirty&&!window.confirm('Discard this unsaved automation edit?'))return;setEdit(null);setAdding(false);setReviewing(null);setError('');}
  async function refresh(){if(busy)return;setBusy(true);try{const r=await fetch(`/api/clients/${accountId}/proposal`,{cache:'no-store'});const data=await r.json() as {proposal:ProposalState;error?:string};if(!r.ok)throw Error(data.error);onSaved(data.proposal);if(reviewing){setReviewing(data.proposal.orders.find(o=>o.key===reviewing.key)||null);setConfirmed(false);}setError('Latest record loaded. Your open fields are retained; compare them before saving.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!proposal?.acceptance)return <section className="company-panel"><h2>Internal automation portfolio</h2><p>Operations is available now. Establish an internal plan to start recording automation work; no customer contract or company-wide onboarding finish is required.</p><Button onClick={onPlan}>Establish internal plan</Button></section>;
  const setupReady=proposal.setup.answers.every(a=>a.trim());
  return <section className="company-panel internal-portfolio"><div className="panel-heading"><div><small className="eyebrow">CONTINUOUS IMPROVEMENT</small><h2>Internal automation portfolio</h2></div><Button disabled={busy} onClick={()=>{setError('');setAdding(true);}}>Add automation</Button></div><p>Build and review each automation independently. Operating means authorized for ongoing internal use—not proof that a harness is running or healthy. Check Services & monitoring for Console observations.</p>{!setupReady&&<div className="company-notice">Save the shared setup context before recording build evidence. <Button variant="outline" onClick={onPlan}>Open internal plan & setup</Button></div>}
    <div className="internal-stage-counts">{['Planned','Building','Testing','Operating'].map(stage=><span key={stage}><b>{proposal.orders.filter(o=>internalStage(o,proposal.setup.revision)===stage).length}</b> {stage}</span>)}</div>
    {proposal.orders.map(o=><article className="internal-order" id={`internal-${o.key}`} key={o.key}><header><h3>{o.name}</h3><span className="company-status">{internalStage(o,proposal.setup.revision)}</span></header>{o.brief&&<p>{o.brief}</p>}<p className="company-help">{o.status==='tested'&&!o.internalRelease?'Testing recorded · internal-use review still needed':`Evidence: ${o.status.replaceAll('_',' ')} · setup revision ${o.setupRevision}`}</p><details><summary>Build, test & safety evidence</summary><p><b>Original scope:</b> {o.brief||Object.entries(proposal.draft.services[o.key as keyof typeof proposal.draft.services]?.config||{}).map(([key,value])=>`${serviceCatalog.find(s=>s.id===o.key)?.fields.find(f=>f.key===key)?.label||key}: ${value}`).join('\n')||proposal.draft.customServices?.find(s=>s.id===o.key)?.outcome||'See saved internal plan'}</p><ol>{(serviceCatalog.find(s=>s.id===o.key)?.steps||['Build the scoped outcome.','Verify permissions, failure handling and human fallback.']).map(step=><li key={step}>{step}</li>)}</ol><p><b>Build:</b> {o.buildRef||'Not recorded'}</p><p><b>Test:</b> {o.testRef||'Not recorded'}</p><p><b>Internal-use review:</b> {o.internalRelease?.review||'Not recorded for this evidence'}</p>{o.internalRelease&&<small>Reviewed by {o.internalRelease.recorded.name} · {o.internalRelease.recorded.at}</small>}</details><EmailWalkthroughLink accountId={accountId} order={o}/><div className="company-actions"><Button variant="outline" disabled={busy||!setupReady} onClick={()=>{setError('');setEdit({...o});}}>Edit build & test</Button>{internalStage(o,proposal.setup.revision)==='Operating'?<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Withdraw internal-use approval? This does not stop the external automation; coordinate that separately.'))void save({action:'withdrawInternal',key:o.key});}}>Withdraw use approval</Button>:<Button disabled={busy||o.status!=='tested'||o.setupRevision!==proposal.setup.revision||!setupReady} onClick={()=>{setError('');setReview('');setConfirmed(false);setReviewing(o);}}>Review for ongoing use</Button>}</div></article>)}
    {error&&!dirty&&<p role="alert" className="company-error">{error} <Button variant="outline" onClick={()=>void refresh()}>Refresh record</Button></p>}
    <Dialog open={dirty} onOpenChange={open=>{if(!open)close();}}><DialogContent className="crm-dialog"><DialogHeader><DialogTitle>{adding?'Add internal automation':reviewing?`Review ${reviewing.name}`:`Build & test: ${edit?.name}`}</DialogTitle><DialogDescription>{reviewing?'Approve this automation only. No other work order is completed, and no deployment is performed.':'Saved changes retain revision history. New or changed evidence requires a fresh internal-use review.'}</DialogDescription></DialogHeader><form className="requirement-editor" onSubmit={e=>{e.preventDefault();if(adding)void save({action:'addInternalOrder',name,brief});else if(reviewing)void save({action:'releaseInternal',key:reviewing.key,review,confirmed});else if(edit)void save({action:'order',key:edit.key,status:edit.status,buildRef:edit.buildRef,testRef:edit.testRef});}}><fieldset disabled={busy}>
      {adding&&<><label>Automation name<Input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Outcome, systems, allowed actions & human fallback<Textarea required maxLength={2000} value={brief} onChange={e=>setBrief(e.target.value)}/></label></>}
      {edit&&<><label>Build & test state<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as WorkOrder['status']})}><option value="to_build">Planned</option><option value="building">Building</option><option value="built">Testing — build ready</option><option value="tested">Tests passed — evidence recorded</option></select></label><label>Build reference / work notes<Textarea maxLength={2000} required={['built','tested'].includes(edit.status)} disabled={edit.status==='to_build'} value={edit.buildRef} onChange={e=>setEdit({...edit,buildRef:e.target.value})}/></label>{edit.status==='tested'&&<label>Test evidence, including failure handling<Textarea required maxLength={2000} value={edit.testRef} onChange={e=>setEdit({...edit,testRef:e.target.value})}/></label>}<p className="company-help">Saving Planned clears current build/test references. Saving Building or Testing clears current test evidence. Any evidence edit withdraws this automation’s use approval; previous records remain in history.</p></>}
      {reviewing&&<><p><b>Build:</b> {reviewing.buildRef}</p><p><b>Test:</b> {reviewing.testRef}</p><label>Safety review: approved actions, access boundaries, human fallback and responsible owner<Textarea required maxLength={2000} value={review} onChange={e=>setReview(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I am authorized to approve this automation for ongoing internal use.</label></>}
    </fieldset>{error&&<div role="alert" className="company-error">{error} Your entries remain here. <Button type="button" variant="outline" disabled={busy} onClick={()=>void refresh()}>Refresh saved version</Button></div>}<DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel</Button><Button type="submit" disabled={busy||!!reviewing&&!confirmed}>{busy?'Saving…':reviewing?'Approve ongoing use':adding?'Add to backlog':'Save evidence'}</Button></DialogFooter></form></DialogContent></Dialog>
  </section>;
}
