"use client";
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, RefreshCw, Search } from 'lucide-react';
import { Button } from './ui/button';
import { useWorkspaceRecords } from './use-workspace-records';
import type { DeliveryReadiness } from '@/lib/delivery-readiness';
import type { ScopingRecord } from '@/lib/server/scoping-work';
import { onboardingStageOptions } from '@/lib/workspace-model';

type Onboarding = {id:string;accountId:string;accountName:string;organizationKind?:string;contactName:string;stage:string;status:string;nextStep:string;targetDate:string;owner:string;total:number;complete:number;blocked:number;readiness:DeliveryReadiness};
const scopeStages=['Prepare scope','Internal review','Client acceptance','Review saved scope'];
export function scopingDestination(item:Pick<ScopingRecord,'accountId'|'stage'>){return `/onboarding/${encodeURIComponent(item.accountId)}?tab=services${item.stage==='Prepare scope'?'':'&step=review'}`;}
export function OnboardingWorkspace(){
  const delivery=useWorkspaceRecords<Onboarding>('/api/onboarding','onboardings');
  const scoping=useWorkspaceRecords<ScopingRecord>('/api/scoping','scoping');
  const deliveryStages=onboardingStageOptions(delivery.records);
  const [query,setQuery]=useState(''),[view,setView]=useState('All work'),[stage,setStage]=useState('All stages');
  const now=new Date();
  const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
  const search=(values:string[])=>values.some(value=>(value||'').toLowerCase().includes(query.trim().toLowerCase()));
  const scopeRows=scoping.records.filter(item=>view!=='Accepted onboarding'&&(stage==='All stages'||stage===item.stage)&&search([item.accountName,item.owner,item.nextAction,item.coordination,item.stage]));
  const deliveryRows=delivery.records.filter(item=>item.organizationKind!=='internal'&&view!=='Preparing scope'&&(stage==='All stages'||stage===item.readiness.stageLabel)&&search([item.accountName,item.contactName,item.owner,item.readiness.label,item.readiness.stageLabel])).sort((a,b)=>Number(b.readiness.stageLabel==='Blocked')-Number(a.readiness.stageLabel==='Blocked')||(a.targetDate||'9999').localeCompare(b.targetDate||'9999')||a.accountName.localeCompare(b.accountName));
  const loading=delivery.loading||scoping.loading;
  const sourceError=(label:string,source:typeof scoping|typeof delivery)=><p role="alert" className="onboarding-source-error">{label}: {source.error} <Button variant="outline" onClick={source.refresh}>Retry</Button></p>;
  return <main className="company-experience onboarding-lane">
    <header className="company-record-header"><div><h1>Onboarding</h1><p>Find the next step, from preparing scope to the final handoff.</p></div><Button variant="outline" disabled={loading} onClick={()=>{scoping.refresh();delivery.refresh();}}><RefreshCw size={16} aria-hidden="true"/>Refresh</Button></header>
    <div className="onboarding-toolbar"><label className="onboarding-search"><Search size={18} aria-hidden="true"/><input aria-label="Search onboarding work" placeholder="Search company, owner or next action" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Show<select value={view} onChange={e=>{setView(e.target.value);setStage('All stages');}}>{['All work','Preparing scope','Accepted onboarding'].map(v=><option key={v}>{v}</option>)}</select></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}>{['All stages',...(view!=='Accepted onboarding'?scopeStages:[]),...(view!=='Preparing scope'?deliveryStages:[])].map(s=><option key={s}>{s}</option>)}</select></label></div>
    {view!=='Accepted onboarding'&&<section className="onboarding-list" aria-labelledby="scope-list-title"><header><div><h2 id="scope-list-title">Preparing scope <span>{scoping.loading?'…':scopeRows.length}</span></h2><p>Service package, internal review and client acceptance.</p></div></header>{scoping.loading&&<p role="status" className="onboarding-empty">Loading saved scope work…</p>}{scoping.error?sourceError('Preparing scope',scoping):scopeRows.map(item=><article className="onboarding-work-row" key={item.id}><div className="onboarding-row-main"><Link href={scopingDestination(item)}><strong>{item.accountName}</strong></Link><p>{item.nextAction}</p>{item.coordination&&item.coordination!==item.nextAction&&<small>Coordination: {item.coordination}</small>}</div><span className="onboarding-stage">{item.stage}</span><div className="onboarding-row-meta"><span>{item.owner||'Unassigned'}</span><small>{item.followUpDate?`Follow-up ${item.followUpDate}`:'No follow-up date'}</small></div><Link className="onboarding-open-link" href={scopingDestination(item)} aria-label={`Open scope for ${item.accountName}`}>Open scope <ArrowRight aria-hidden="true" size={16}/></Link></article>)}{!scoping.loading&&!scoping.error&&!scopeRows.length&&<p className="onboarding-empty">{query||stage!=='All stages'?'No scope work matches these filters.':'No companies are waiting for scope. Start a client workflow from Inbox, or open a company to prepare its service package.'} <Link href="/communications">Open Inbox</Link></p>}</section>}
    {view!=='Preparing scope'&&<section className="onboarding-list" aria-labelledby="delivery-list-title"><header><div><h2 id="delivery-list-title">Accepted onboarding <span>{delivery.loading?'…':deliveryRows.length}</span></h2><p>Setup, build evidence and handoff. Earlier delivery plans remain available.</p></div></header>{delivery.loading&&<p role="status" className="onboarding-empty">Loading saved delivery work…</p>}{delivery.error?sourceError('Accepted onboarding',delivery):deliveryRows.map(item=><article className="onboarding-work-row" key={item.id}><div className="onboarding-row-main"><Link href={`/onboarding/${encodeURIComponent(item.accountId)}?tab=delivery`}><strong>{item.accountName}</strong></Link><p>{item.readiness.label}</p><small>{item.complete}/{item.total} requirements resolved{item.readiness.legacy?' · Earlier delivery plan':''}{item.blocked>0?` · ${item.blocked} blocked`:''}</small></div><span className="onboarding-stage">{item.readiness.stageLabel}</span><div className="onboarding-row-meta"><span>{item.owner||'Unassigned'}</span><small>{item.targetDate?`${item.targetDate<today?'Past target':'Target'} ${item.targetDate}`:'No target date'}</small></div><Link className="onboarding-open-link" href={`/onboarding/${encodeURIComponent(item.accountId)}?tab=delivery`} aria-label={`Continue onboarding for ${item.accountName}`}>Continue <ArrowRight aria-hidden="true" size={16}/></Link></article>)}{!delivery.loading&&!delivery.error&&!deliveryRows.length&&<p className="onboarding-empty">{query||stage!=='All stages'?'No delivery work matches these filters.':'Accepted engagements appear here when delivery begins.'} <Link href="/companies">View companies</Link></p>}</section>}
  </main>;
}
